accountManager = false
newPlayerChooseVoc = false
namelockManager = true
newPlayerChooseTown = false
newPlayerLevel = 1
newPlayerMagicLevel = 0
generateAccountNumber = false
generateAccountSalt = false
maxItemsPerPZTile = 0
maxItemsPerHouseTile = 0
useFragHandler = true
redSkullLength = 30 * 24 * 60 * 60
blackSkullLength = 45 * 24 * 60 * 60
dailyFragsToRedSkull = 10
weeklyFragsToRedSkull = 15
monthlyFragsToRedSkull = 20
dailyFragsToBlackSkull = dailyFragsToRedSkull
weeklyFragsToBlackSkull = weeklyFragsToRedSkull
monthlyFragsToBlackSkull = monthlyFragsToRedSkull
dailyFragsToBanishment = dailyFragsToRedSkull
weeklyFragsToBanishment = weeklyFragsToRedSkull
monthlyFragsToBanishment = monthlyFragsToRedSkull
blackSkulledDeathHealth = 40
blackSkulledDeathMana = 0
useBlackSkull = true
advancedFragList = true
notationsToBan = 3
warningsToFinalBan = 4
warningsToDeletion = 5
banLength = 7 * 24 * 60 * 60
killsBanLength = 0
finalBanLength = 30 * 24 * 60 * 60
ipBanishmentLength = 1 * 24 * 60 * 60
broadcastBanishments = true
maxViolationCommentSize = 250
violationNameReportActionType = 2
autoBanishUnknownBytes = false
max_heap_size = 4096
worldType = "2"
protectionLevel = 40
pvpTileIgnoreLevelAndVocationProtection = true
pzLocked = 60000
huntingDuration = 60 * 1000
criticalHitChance = 7
criticalHitMultiplier = 1
displayCriticalHitNotify = true
removeWeaponAmmunition = true
removeWeaponCharges = true
removeRuneCharges = true
whiteSkullTime = 15
noDamageToSameLookfeet = false
showHealingDamage = true
showHealingDamageForMonsters = true
fieldOwnershipDuration = 5 * 1000
stopAttackingAtExit = true
loginProtectionPeriod = 10 * 1000
deathLostPercent = 10
stairhopDelay = 2 * 1000
pushCreatureDelay = 2 * 1000
deathContainerId = 1987
gainExperienceColor = 215
addManaSpentInPvPZone = true
squareColor = 0
allowFightback = true
fistBaseAttack = 7
optionalWarAttackableAlly = false
worldId = 0
ip = "thp.servegame.com"
loginPort = 7171
gamePort = 7172
loginTries = 3
retryTimeout = 5 * 1000
loginTimeout = 60 * 1000
maxPlayers = 300
motd = "Bem vindo ao Tbia Harry Potter Origin!"
displayOnOrOffAtCharlist = false
onePlayerOnlinePerAccount = false
allowClones = false
serverName = "THPO"
loginMessage = "Bem vindo ao Tibia Harry Potter Origin!"
statusTimeout = 2
replaceKickOnLogin = true
forceSlowConnectionsToDisconnect = false
loginOnlyWithLoginServer = false
premiumPlayerSkipWaitList = false



sqlType = "mysql"
sqlHost = "177.54.147.142"

sqlPort = 3306
sqlUser = "thpocom1_root"

sqlPass = "" 

sqlDatabase = "thpocom1_thpo"

sqlFile = "hpmysql.sql"
sqlKeepAlive = 0
mysqlReadTimeout = 28800
mysqlWriteTimeout = 28800
encryptionType = "sha1"

deathListEnabled = true
deathListRequiredTime = 1 * 60 * 1000
deathAssistCount = 5
maxDeathRecords = 10

ingameGuildManagement = false
levelToFormGuild = 100
premiumDaysToFormGuild = 0
onBuy = 700
onSell = 700
changeOutfit = 500

guildNameMinLength = 4
guildNameMaxLength = 20
highscoreDisplayPlayers = 10
updateHighscoresAfterMinutes = 60
buyableAndSellableHouses = true
houseNeedPremium = true
bedsRequirePremium = true
levelToBuyHouse = 100
housesPerAccount = 0
houseRentAsPrice = false
housePriceAsRent = false
housePriceEachSquare = 4200
houseRentPeriod = "never"
houseCleanOld = 0
guildHalls = false
timeBetweenActions = 0
timeBetweenExActions = 1000
hotkeyAimbotEnabled = true
mapName = "harry.otbm"
mapAuthor = "L3K0T"
randomizeTiles = true
storeTrash = true
cleanProtectedZones = true
mailboxDisabledTowns = ""
defaultPriority = "high"
niceLevel = 5
coresUsed = "5"
startupDatabaseOptimization = true
updatePremiumStateAtStartup = true
confirmOutdatedVersion = false
skipItemsVersionCheck = true
formulaLevel = 5.0
formulaMagic = 1.0
bufferMutedOnSpellFailure = false
spellNameInsteadOfWords = false
emoteSpells = true
allowChangeOutfit = true
allowChangeColors = true
allowChangeAddons = true
disableOutfitsForPrivilegedPlayers = false
addonsOnlyPremium = true
dataDirectory = "data/"
logsDirectory = "data/logs/"
bankSystem = false
displaySkillLevelOnAdvance = true
promptExceptionTracerErrorBox = true
maximumDoorLevel = 500
maxMessageBuffer = 4
separateVipListPerCharacter = false
vipListDefaultLimit = 20
vipListDefaultPremiumLimit = 100
saveGlobalStorage = true
useHouseDataStorage = true
storePlayerDirection = false
checkCorpseOwner = true
monsterLootMessage = 3
monsterLootMessageType = 25
ghostModeInvisibleEffect = true
ghostModeSpellEffects = true
idleWarningTime = 14 * 60 * 1000
idleKickTime = 15 * 60 * 1000
reportsExpirationAfterReads = 1
playerQueryDeepness = 1
tileLimit = 8
protectionTileLimit = 8
houseTileLimit = 8
freePremium = false
premiumForPromotion = true
blessings = true
blessingOnlyPremium = true
blessingReductionBase = 30
blessingReductionDecrement = 5
eachBlessReduction = 8
experienceStages = true
rateExperience = 3
rateExperienceFromPlayers = 3
rateSkill = 5.0
rateMagic = 5.5
rateLoot = 3.0
rateSpawn = 1
rateMonsterHealth = 1.0
rateMonsterMana = 1.0
rateMonsterAttack = 1.0
rateMonsterDefense = 1.0
minLevelThresholdForKilledPlayer = 0.9
maxLevelThresholdForKilledPlayer = 1.1
rateStaminaLoss = 1
rateStaminaGain = 3
rateStaminaThresholdGain = 12
staminaRatingLimitTop = 40 * 60
staminaRatingLimitBottom = 14 * 60
staminaLootLimit = 14 * 60
rateStaminaAboveNormal = 1.5
rateStaminaUnderNormal = 0.5
staminaThresholdOnlyPremium = true
experienceShareRadiusX = 30
experienceShareRadiusY = 30
experienceShareRadiusZ = 1
experienceShareLevelDifference = 2 / 3
extraPartyExperienceLimit = 20
extraPartyExperiencePercent = 5
experienceShareActivity = 2 * 60 * 1000
globalSaveEnabled = false
globalSaveHour = 4
globalSaveMinute = 59
shutdownAtGlobalSave = false
cleanMapAtGlobalSave = false
deSpawnRange = 2
deSpawnRadius = 50
maxPlayerSummons = 1
teleportAllSummons = true
teleportPlayerSummons = true
statusPort = 7171
ownerName = "THP - Tibia harry Potter Origin"
ownerEmail = ""
url = "thp.servegame.com"
location = "Brazil"
displayGamemastersWithOnlineCommand = false
displayPlayersLogging = true
prefixChannelLogs = ""
runFile = ""
outputLog = ""
truncateLogsOnStartup = false
managerPort = 7171
managerLogs = true
managerPassword = "56756753244rrgfh34554756745345&*"
managerLocalhostOnly = true
managerConnectionsLimit = 1
adminPort = 7171
adminLogs = true
adminPassword = "56756753244rrgfh34554756745345&*"
adminLocalhostOnly = true
adminConnectionsLimit = 1
adminRequireLogin = true
adminEncryption = ""
adminEncryptionData = ""
advertisingBlock = "servegame", "quilante", "xvideo", "vai.la", "no-ip", ".net", ".com", ".org", "biz", ".br", "sytes", ".info", "vai.la"
max_packets_per_second = 10000
enableCast = true